ci improvements

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,11 +49,12 @@ jobs:
         run: |
           rm ${HOME}/.config/chezmoi/key.txt
 
-      - uses: GuillaumeFalourd/assert-command-line-output@v2.1
-        with:
-          command_line: ${HOME}/.local/bin/chezmoi data --format=yaml
-          contains: "is_desktop: true"
-          expected_result: PASSED
+      - name: assert
+        run: |
+          if ! grep -q is_desktop ${HOME}/.config/chezmoi/chezmoi.yaml; then
+            echo 'is_desktop: true' not found
+            echo "::error file=chezmoi.yaml::is_desktop: true not found"
+          fi
 
   linux-server:
     strategy:
